route:
  receiver: 'email-receiver'
  group_wait: 30s            # Wait before sending the first notification
  group_interval: 5m         # Wait 5 minutes before grouping notifications
  repeat_interval: 5m 

receivers:
  - name: 'email-receiver'
    email_configs:
      - to: ''
        from: ''
        smarthost: 'smtp.gmail.com:587' # Use Gmail's SMTP server
        auth_username: '' # Your Gmail address
        auth_password: '************' # Google App Password
        require_tls: true
